name : CI Workflow for my App

# execute the flow only when a push or pull request is made to the main branch
on:
  push:
    branches: #specify the branches to trigger the workflow
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in this workflow
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest _test.py
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml